// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecruitPro.Infrastructure.Data;

#nullable disable

namespace RecruitPro.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619081050_MergeCandidateSkillYearsIntoCandidateSkills")]
    partial class MergeCandidateSkillYearsIntoCandidateSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecruitPro.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("cover_letter");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("final_score");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<decimal?>("RuleScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rule_score");

                    b.Property<string>("ScoreError")
                        .HasColumnType("text")
                        .HasColumnName("score_error");

                    b.Property<string>("ScoreStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("score_status");

                    b.Property<DateTime?>("ScoredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scored_at");

                    b.Property<decimal?>("SemanticScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("semantic_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("applications_pkey");

                    b.HasIndex("JobId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("UserId");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.ApplicationOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("base_salary");

                    b.Property<string>("BonusDescription")
                        .HasColumnType("text")
                        .HasColumnName("bonus_description");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employment_type");

                    b.Property<string>("EquityNotes")
                        .HasColumnType("text")
                        .HasColumnName("equity_notes");

                    b.Property<Guid?>("OfferTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_template_id");

                    b.Property<string>("PersonalMessage")
                        .HasColumnType("text")
                        .HasColumnName("personal_message");

                    b.Property<string>("ProbationPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("probation_period");

                    b.Property<DateTime?>("ProposedStartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("proposed_start_date");

                    b.Property<Guid?>("ReportingManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporting_manager_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("application_offers_pkey");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("OfferTemplateId");

                    b.HasIndex("ReportingManagerId");

                    b.HasIndex(new[] { "ApplicationId" }, "application_offers_application_id_key")
                        .IsUnique();

                    b.ToTable("application_offers", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.ApplicationOfferBenefit", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid>("BenefitId")
                        .HasColumnType("uuid")
                        .HasColumnName("benefit_id");

                    b.HasKey("OfferId", "BenefitId")
                        .HasName("application_offer_benefits_pkey");

                    b.HasIndex("BenefitId");

                    b.ToTable("application_offer_benefits", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("CandidateEmbeddingError")
                        .HasColumnType("text")
                        .HasColumnName("candidate_embedding_error");

                    b.Property<string>("CandidateEmbeddingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("candidate_embedding_status");

                    b.Property<string>("CandidateEmbeddingTextHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("candidate_embedding_text_hash");

                    b.Property<DateTime?>("CandidateEmbeddingUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("candidate_embedding_updated_at");

                    b.Property<string>("CandidateEmbeddingVectorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("candidate_embedding_vector");

                    b.Property<string>("CertificationRecordsJson")
                        .HasColumnType("text")
                        .HasColumnName("certification_records_json");

                    b.Property<string>("CurrentPosition")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("current_position");

                    b.Property<string>("Education")
                        .HasColumnType("text")
                        .HasColumnName("education");

                    b.Property<string>("EducationRecordsJson")
                        .HasColumnType("text")
                        .HasColumnName("education_records_json");

                    b.Property<string>("ExperienceEntriesJson")
                        .HasColumnType("text")
                        .HasColumnName("experience_entries_json");

                    b.Property<int?>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("experience_years");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("text")
                        .HasColumnName("github_url");

                    b.Property<string>("LanguageRecordsJson")
                        .HasColumnType("text")
                        .HasColumnName("language_records_json");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("ParsedResumeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_resume_json");

                    b.Property<string>("ResumeExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("resume_extracted_text");

                    b.Property<string>("ResumeParseError")
                        .HasColumnType("text")
                        .HasColumnName("resume_parse_error");

                    b.Property<string>("ResumeParseModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resume_parse_model");

                    b.Property<string>("ResumeParseStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resume_parse_status");

                    b.Property<DateTime?>("ResumeParsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resume_parsed_at");

                    b.Property<string>("ResumeParserWarningsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("resume_parser_warnings_json");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text")
                        .HasColumnName("resume_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("candidate_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "candidate_profiles_user_id_key")
                        .IsUnique();

                    b.ToTable("candidate_profiles", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("integer")
                        .HasColumnName("end_month");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role");

                    b.Property<int>("StartMonth")
                        .HasColumnType("integer")
                        .HasColumnName("start_month");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.Property<string>("TechnologiesJson")
                        .HasColumnType("text")
                        .HasColumnName("technologies_json");

                    b.HasKey("Id")
                        .HasName("candidate_projects_pkey");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("candidate_projects", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateResume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_profile_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("upload_date");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("candidate_resumes_pkey");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("candidate_resumes", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<decimal?>("YearsOfExperience")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("years_of_experience");

                    b.HasKey("CandidateId", "SkillId")
                        .HasName("candidate_skills_pkey");

                    b.HasIndex("SkillId");

                    b.ToTable("candidate_skills", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotCandidateTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CandidateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("RankingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ranking_session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("AI")
                        .HasColumnName("source");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tag_name");

                    b.HasKey("Id")
                        .HasName("copilot_candidate_tags_pkey");

                    b.HasIndex("CandidateUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RankingSessionId");

                    b.HasIndex(new[] { "JobId", "TagName" }, "ix_copilot_candidate_tags_job_tag");

                    b.ToTable("copilot_candidate_tags", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("LatestRankingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_ranking_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("copilot_conversations_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "JobId", "UserId", "CreatedAt" }, "ix_copilot_conversations_job_user_created_at");

                    b.HasIndex(new[] { "LatestRankingSessionId" }, "ix_copilot_conversations_latest_ranking_session_id");

                    b.HasIndex(new[] { "JobId", "UserId" }, "ux_copilot_conversations_active_job_user")
                        .IsUnique()
                        .HasFilter("status = 'Active'");

                    b.ToTable("copilot_conversations", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.HasKey("Id")
                        .HasName("copilot_messages_pkey");

                    b.HasIndex(new[] { "ConversationId", "SequenceNo" }, "ix_copilot_messages_conversation_sequence");

                    b.ToTable("copilot_messages", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotRankingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("CandidateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("EducationScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("education_score");

                    b.Property<decimal>("ExperienceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("experience_score");

                    b.Property<string>("ExplanationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("explanation_json");

                    b.Property<bool>("IsAutoRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_auto_rejected");

                    b.Property<decimal>("ProjectScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("project_score");

                    b.Property<int>("RankPosition")
                        .HasColumnType("integer")
                        .HasColumnName("rank_position");

                    b.Property<Guid>("RankingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ranking_session_id");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("recommendation");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<decimal>("SkillScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("skill_score");

                    b.Property<string>("StrengthsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("strengths_json");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("total_score");

                    b.Property<string>("WeaknessesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weaknesses_json");

                    b.HasKey("Id")
                        .HasName("copilot_ranking_results_pkey");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CandidateUserId");

                    b.HasIndex(new[] { "RankingSessionId", "RankPosition" }, "ix_copilot_ranking_results_session_rank");

                    b.HasIndex(new[] { "RankingSessionId", "IsAutoRejected", "TotalScore" }, "ix_copilot_ranking_results_session_reject_score");

                    b.ToTable("copilot_ranking_results", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotRankingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("NormalizedRulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_rules_json");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<int>("TotalCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("total_candidates");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_prompt");

                    b.HasKey("Id")
                        .HasName("copilot_ranking_sessions_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ConversationId", "CreatedAt" }, "ix_copilot_ranking_sessions_conversation_created_at");

                    b.HasIndex(new[] { "JobId", "CreatedAt" }, "ix_copilot_ranking_sessions_job_created_at");

                    b.ToTable("copilot_ranking_sessions", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotSavedRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RuleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("copilot_saved_rules_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "JobId", "IsActive" }, "ix_copilot_saved_rules_job_active");

                    b.HasIndex(new[] { "JobId", "UserId", "UpdatedAt" }, "ix_copilot_saved_rules_job_user_updated_at");

                    b.ToTable("copilot_saved_rules", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("departments_pkey");

                    b.HasIndex(new[] { "Name" }, "departments_name_key")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("interview_date");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text")
                        .HasColumnName("meeting_link");

                    b.Property<string>("MeetingType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("meeting_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("interviews_pkey");

                    b.HasIndex("ApplicationId");

                    b.ToTable("interviews", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("Benefits")
                        .HasColumnType("text")
                        .HasColumnName("benefits");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employment_type");

                    b.Property<string>("JobEmbeddingError")
                        .HasColumnType("text")
                        .HasColumnName("job_embedding_error");

                    b.Property<string>("JobEmbeddingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job_embedding_status");

                    b.Property<string>("JobEmbeddingTextHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_embedding_text_hash");

                    b.Property<DateTime?>("JobEmbeddingUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("job_embedding_updated_at");

                    b.Property<string>("JobEmbeddingVectorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("job_embedding_vector");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<int?>("MinExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("min_experience_years");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("salary_min");

                    b.Property<string>("ShortPitch")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_pitch");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int?>("VacancyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("vacancy_count");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("work_mode");

                    b.HasKey("Id")
                        .HasName("jobs_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<decimal?>("MinYearsExperience")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("min_years_experience");

                    b.HasKey("JobId", "SkillId")
                        .HasName("job_skills_pkey");

                    b.HasIndex("SkillId");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.OfferBenefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("offer_benefits_pkey");

                    b.ToTable("offer_benefits", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.OfferCurrency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.HasKey("Code")
                        .HasName("offer_currencies_pkey");

                    b.ToTable("offer_currencies", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.OfferTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_body");

                    b.HasKey("Id")
                        .HasName("offer_templates_pkey");

                    b.ToTable("offer_templates", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("permissions_pkey");

                    b.HasIndex(new[] { "Code" }, "permissions_code_key")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("role_permissions_pkey");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("skills_pkey");

                    b.HasIndex(new[] { "Name" }, "skills_name_key")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.SystemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("system_logs_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("system_logs", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Application", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applications_job_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "ReviewedByNavigation")
                        .WithMany("ApplicationReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("applications_reviewed_by_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applications_user_id_fkey");

                    b.Navigation("Job");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.ApplicationOffer", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Application", "Application")
                        .WithOne("Offer")
                        .HasForeignKey("RecruitPro.Domain.Entities.ApplicationOffer", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_offers_application_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.OfferCurrency", "Currency")
                        .WithMany("ApplicationOffers")
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_offers_currency_code_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.OfferTemplate", "OfferTemplate")
                        .WithMany("ApplicationOffers")
                        .HasForeignKey("OfferTemplateId")
                        .HasConstraintName("application_offers_offer_template_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "ReportingManagerNavigation")
                        .WithMany("ReportingManagerOffers")
                        .HasForeignKey("ReportingManagerId")
                        .HasConstraintName("application_offers_reporting_manager_id_fkey");

                    b.Navigation("Application");

                    b.Navigation("Currency");

                    b.Navigation("OfferTemplate");

                    b.Navigation("ReportingManagerNavigation");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.ApplicationOfferBenefit", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.OfferBenefit", "Benefit")
                        .WithMany("ApplicationOfferBenefits")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_offer_benefits_benefit_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.ApplicationOffer", "Offer")
                        .WithMany("ApplicationOfferBenefits")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_offer_benefits_offer_id_fkey");

                    b.Navigation("Benefit");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateProfile", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("RecruitPro.Domain.Entities.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("candidate_profiles_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateProject", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("Projects")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("candidate_projects_candidate_profile_id_fkey");

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateResume", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("Resumes")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("candidate_resumes_candidate_profile_id_fkey");

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateSkill", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.CandidateProfile", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("candidate_skills_candidate_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("candidate_skills_skill_id_fkey");

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotCandidateTag", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.User", "CandidateUser")
                        .WithMany()
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_candidate_tags_candidate_user_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_candidate_tags_created_by_user_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_candidate_tags_job_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.CopilotRankingSession", "RankingSession")
                        .WithMany()
                        .HasForeignKey("RankingSessionId")
                        .HasConstraintName("copilot_candidate_tags_ranking_session_id_fkey");

                    b.Navigation("CandidateUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Job");

                    b.Navigation("RankingSession");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotConversation", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_conversations_job_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.CopilotRankingSession", "LatestRankingSession")
                        .WithMany()
                        .HasForeignKey("LatestRankingSessionId")
                        .HasConstraintName("copilot_conversations_latest_ranking_session_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_conversations_user_id_fkey");

                    b.Navigation("Job");

                    b.Navigation("LatestRankingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotMessage", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.CopilotConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_messages_conversation_id_fkey");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotRankingResult", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_ranking_results_application_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "CandidateUser")
                        .WithMany()
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_ranking_results_candidate_user_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.CopilotRankingSession", "RankingSession")
                        .WithMany("Results")
                        .HasForeignKey("RankingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_ranking_results_ranking_session_id_fkey");

                    b.Navigation("Application");

                    b.Navigation("CandidateUser");

                    b.Navigation("RankingSession");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotRankingSession", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.CopilotConversation", "Conversation")
                        .WithMany("RankingSessions")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_ranking_sessions_conversation_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_ranking_sessions_job_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_ranking_sessions_user_id_fkey");

                    b.Navigation("Conversation");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotSavedRule", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_saved_rules_job_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("copilot_saved_rules_user_id_fkey");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Interview", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Application", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("interviews_application_id_fkey");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Job", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.User", "ApprovedByNavigation")
                        .WithMany("JobApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("jobs_approved_by_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("JobCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("jobs_created_by_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.Department", "Department")
                        .WithMany("Jobs")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("jobs_department_id_fkey");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_skills_job_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_skills_skill_id_fkey");

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Notification", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_permission_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_role_id_fkey");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.SystemLog", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithMany("SystemLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("system_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("RecruitPro.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("RecruitPro.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Application", b =>
                {
                    b.Navigation("Interviews");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.ApplicationOffer", b =>
                {
                    b.Navigation("ApplicationOfferBenefits");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CandidateProfile", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("Projects");

                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("RankingSessions");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.CopilotRankingSession", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Department", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.OfferBenefit", b =>
                {
                    b.Navigation("ApplicationOfferBenefits");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.OfferCurrency", b =>
                {
                    b.Navigation("ApplicationOffers");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.OfferTemplate", b =>
                {
                    b.Navigation("ApplicationOffers");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.Skill", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("RecruitPro.Domain.Entities.User", b =>
                {
                    b.Navigation("ApplicationReviewedByNavigations");

                    b.Navigation("Applications");

                    b.Navigation("CandidateProfile");

                    b.Navigation("JobApprovedByNavigations");

                    b.Navigation("JobCreatedByNavigations");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReportingManagerOffers");

                    b.Navigation("SystemLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
